######################################################################
# Automatically generated by qmake (1.07a) Fri Oct 14 10:12:31 2005
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += qxtable.h
SOURCES += main.cpp qxtable.cpp
