/****************************************************************************
**
** DCOP Skeleton generated by dcopidl2cpp from kuireiface.kidl
**
** WARNING! All changes made in this file will be lost!
**
*****************************************************************************/

#include "/home/cnikiel/Projects/kuire/src/kuireiface.h"

#include <kdatastream.h>


static const char* const KuireIface_ftable[2][3] = {
    { "void", "openURL(QString)", "openURL(QString url)" },
    { 0, 0, 0 }
};
static const int KuireIface_ftable_hiddens[1] = {
    0,
};

bool KuireIface::process(const QCString &fun, const QByteArray &data, QCString& replyType, QByteArray &replyData)
{
    if ( fun == KuireIface_ftable[0][1] ) { // void openURL(QString)
	QString arg0;
	QDataStream arg( data, IO_ReadOnly );
	if (arg.atEnd()) return false;
	arg >> arg0;
	replyType = KuireIface_ftable[0][0]; 
	openURL(arg0 );
    } else {
	return DCOPObject::process( fun, data, replyType, replyData );
    }
    return true;
}

QCStringList KuireIface::interfaces()
{
    QCStringList ifaces = DCOPObject::interfaces();
    ifaces += "KuireIface";
    return ifaces;
}

QCStringList KuireIface::functions()
{
    QCStringList funcs = DCOPObject::functions();
    for ( int i = 0; KuireIface_ftable[i][2]; i++ ) {
	if (KuireIface_ftable_hiddens[i])
	    continue;
	QCString func = KuireIface_ftable[i][0];
	func += ' ';
	func += KuireIface_ftable[i][2];
	funcs << func;
    }
    return funcs;
}


